replicaCount:
  service: 1

# Add your service-specific values here
# service:
#   host: localhost
#   port: 8080

resources:
  limits:
    cpu: "300m"
    memory: "2Gi"
  requests:
    cpu: "100m"
    memory: "400Mi"

